### PR TITLE
fixes bug where rankby and radius used together (Bug #18)

### PR DESCRIPTION
**Pull request by AppSorcery**

### CODE REVIEW

**Comment by codewinkel** [comment]
Could someone merge this fix, please!?

**Comment by codewinkel** [comment]
Nice, could you also release a new version?

**Comment by Srirangan** [comment]
as soon as NPM lets me, i get a 405 right now

**Comment by codewinkel** [comment]
ok

**Comment by Srirangan** [comment]
0.6.1 :+1:

**Comment by codewinkel** [comment]
Great

**Pull request merged**
